from pyspark.sql import functions as F
from feature_engineering.observability import traced
@traced()
def build_point_in_time_features(q,h,f,cfg):
 j=q.alias("q").join(h.alias("h"),(F.col("h.launch_date")<F.col("q.launch_date"))&F.col("h.m3_qty").isNotNull(),"left")
 p=j.groupBy(F.col("q.product_id").alias("product_id")).agg(F.sum(F.when(F.col("h.brand")==F.col("q.brand"),1).otherwise(0)).alias("brand_historical_launch_count"),F.avg(F.when(F.col("h.brand")==F.col("q.brand"),F.col("h.qty_90d"))).alias("brand_avg_first_90d_qty"),F.sum(F.when(F.col("h.functional_category")==F.col("q.functional_category"),1).otherwise(0)).alias("category_historical_launch_count"),F.avg(F.when(F.col("h.functional_category")==F.col("q.functional_category"),F.col("h.qty_90d"))).alias("category_avg_first_90d_qty"),F.expr("percentile_approx(case when h.functional_category=q.functional_category then h.launch_price end,.5)").alias("cm"),F.expr("percentile_approx(case when h.brand=q.brand then h.launch_price end,.5)").alias("bm"),F.avg(F.when((F.col("h.functional_category")==F.col("q.functional_category"))&(F.col("h.launch_price")<=F.col("q.launch_price")),1.0).otherwise(0.0)).alias("category_price_percentile"))
 p=p.join(q.select("product_id","launch_price"),"product_id").withColumn("price_to_category_median",F.col("launch_price")/F.greatest("cm",F.lit(1.0))).withColumn("price_to_brand_median",F.col("launch_price")/F.greatest("bm",F.lit(1.0)))
 x=q.alias("q").join(f.alias("f"),(F.col("f.order_date")<F.col("q.launch_date"))&(F.col("f.order_date")>=F.date_sub(F.col("q.launch_date"),cfg.lookback_days))&(F.col("f.functional_category")==F.col("q.functional_category")),"left")
 d=x.groupBy(F.col("q.product_id").alias("product_id")).agg(F.sum(F.when(F.col("f.order_date")>=F.date_sub(F.col("q.launch_date"),cfg.recent_days),F.col("f.quantity")).otherwise(0)).alias("category_recent_demand"),F.sum(F.when(F.col("f.order_date")<F.date_sub(F.col("q.launch_date"),cfg.recent_days),F.col("f.quantity")).otherwise(0)).alias("prev"),F.sum(F.when(F.month("f.order_date")==F.month("q.launch_date"),F.col("f.quantity")).otherwise(0)).alias("same"),F.sum("f.quantity").alias("total")).withColumn("category_demand_trend",(F.col("category_recent_demand")+1)/(F.col("prev")+1)).withColumn("category_launch_month_index",F.col("same")/F.greatest(F.col("total")/12,F.lit(1.0)))
 e=q.alias("q").join(f.alias("f"),(F.col("f.order_date")<F.col("q.launch_date"))&((F.col("f.brand")==F.col("q.brand"))|(F.col("f.functional_category")==F.col("q.functional_category"))),"left").groupBy(F.col("q.product_id").alias("product_id")).agg(F.countDistinct("f.customer_id").alias("eligible_customer_count"))
 return p.join(d,"product_id","left").join(e,"product_id","left").select("product_id","price_to_category_median","price_to_brand_median","category_price_percentile","brand_historical_launch_count","brand_avg_first_90d_qty","category_historical_launch_count","category_avg_first_90d_qty","category_recent_demand","category_demand_trend","category_launch_month_index","eligible_customer_count")